### ISSUE TITLE
broken links in README.md

### ISSUE THREAD

**Issue by giuliomoro** [reduzent/netpd#46]
At least these don't work:

https://www.netpd.org/Chat
https://www.netpd.org/Unpatch
https://www.netpd.org/sine
https://www.netpd.org/master
https://www.netpd.org/Server
https://www.netpd.org/Instruments

**Comment by reduzent** [comment]
Oops..  I migrated the site from ZWiki to Hugo which changed most links. Thanks for reporting this!
