### ISSUE TITLE
unstep: missing gui elements?

### ISSUE THREAD

**Issue by fpiesik** [reduzent/netpd#5]
I've never seen the gui of unstep somewhere else but I assume that there are faders missing which assign to the tabs "drive",  "attack" and "decay" (see screenshot below). The pd terminal doesn't indicate any missing libraries, though...
![image](https://cloud.githubusercontent.com/assets/1476763/11778223/5b206eb6-a253-11e5-9768-afc24ded3fd5.png)

**Comment by reduzent** [comment]
You're absolutely right. The GUI is a bit finicky as it requires you to grab the corners of the pink bars. Move the pointer exactly above one of the pink lines, click and drag from there. You should be able to drag them up. You can have totally independent settings for 'drive', 'attack' and 'decay'.

**Comment by fpiesik** [comment]
got it - this is a really cool project, tanks for that!
