### ISSUE TITLE
pd crash with "Pd: signal 6"

### ISSUE THREAD

**Issue by vjx** [reduzent/netpd#6]
Pd crashes with "Pd: signal 6" as soon as I change the tempo in the master patch.
Tried with jack and Alsa output.
using pd 0.50.0   on xubuntu 18.04.4

**Comment by reduzent** [comment]
Thanks for the report. 

Can you tell me whether you see any errors in the Pd console? If so, please tell me about them.

I noticed that you tried when someone else was online too. I know from this person that they were struggling as well and I cannot rule out with absolute certainty that your troubles are not related to theirs as they tried some unorthodox things.

Maybe best is to come to #dataflow again and figure out issues bilaterally. My nick is rdz and I also try to be logged into netpd.

**Comment by reduzent** [comment]
We did run netpd together and the problem seems to have vanished. I close this issue. Please re-open, if issue re-appears.
