### ISSUE TITLE
missing external in prerequisites list?

### ISSUE THREAD

**Issue by nooisy** [reduzent/netpd#7]
While starting up netpd for the first time with vanilla Pd (0.50.2) I got the following error:
```
dir
... couldn't create
[tcpclient]: unable to connect to stream socket
connect: Unknown error (10049)
```
After some searching around it became apparent that the [dir] object comes with the [ELSE library](https://github.com/porres/pd-else), which isn't mentioned in the prerequisites list. I saw other people run into this problem as well, did we miss something or is this indeed missing from the list?

But I'm excited that it's working now! Thanks a lot for netpd :)

**Comment by reduzent** [comment]
Indeed, the README.txt was (and still is to some degree) outdated. Thanks for the pointer. I fixed the most pressing issues, namely the dependency list.
