### ISSUE TITLE
pd 0.51-1 - netpd text glitches

### ISSUE THREAD

**Issue by nofoto** [reduzent/netpd#8]
With the latest version of pd 0.51-1 installed (on mac) netpd has gone a bit glitchy in the text boxes of the chat and unpatch - slashes '\' appearing at every space.

**Comment by reduzent** [comment]
Thanks for telling me. Do you mind posting a screenshot of chat and unpatch?

**Comment by nofoto** [comment]
![Screen Shot 2020-09-01 at 15 19 53](https://user-images.githubusercontent.com/31951459/91856379-cd18df00-ec66-11ea-806d-9c2443e1cfe2.png)
![Screen Shot 2020-09-01 at 15 21 47](https://user-images.githubusercontent.com/31951459/91856475-ea4dad80-ec66-11ea-8490-cb9b24737db0.png)

**Comment by nofoto** [comment]
the chat is okay once it is sent - it's just weird in the box you type in.

**Comment by reduzent** [comment]
I agree it is ugly and I would like the ugly backslashes to disappear. However, it's not something that can be fixed in netpd. It should be addressed in Pd's symbol atom.

**Comment by reduzent** [comment]
Here is the relevant issue: https://github.com/pure-data/pure-data/issues/824

**Comment by reduzent** [comment]
The relevant issue is now here: https://github.com/pure-data/pure-data/issues/1477
